[package]
name = "udp53_lookup"
version = "0.1.0"
authors = ["CatMe0w <catme0w@live.cn>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trust-dns-resolver = "0.20.3"

[profile.release]
panic = 'abort'
lto = true